### ISSUE TITLE
Почему то не работает

### ISSUE THREAD

**Issue by tellts** [danilkolikov/logowriter#1]
Здравствуйте. Открыл в Chrome. Что-то не то.
[https://s8.hostingkartinok.com/uploads/images/2020/07/8e091a0b6a72d4f9a2d3a3ec135b420a.jpg](url)

**Comment by danilkolikov** [comment]
Добрый день, @tellts. 

Страница открывается корректно в Firefox v76:
![image](https://user-images.githubusercontent.com/12239684/87851772-e272bd80-c8f3-11ea-827e-0eafa904e80f.png)

Я не обновлял проект уже много лет, видимо за это время Chrome начал блокировать часть используемых функций. 

Превью было реализовано через IFrame, и скорее всего именно это и сломалось. Попробуйте скачать репозиторий и открыть страницу локально, это должно решить пробему. 

Если же необходима работа именно в Chrome и нет возможности запускать скрипт локально, то я рекомендую использовать другие реализации интерпретатора. Например, эту: [Logo Interpretator](https://www.calormen.com/jslogo/).

**Comment by tellts** [comment]
Благодарю за ответ.
